[workspace]
members = ["day??"]

resolver = "2"
# Optimize all dependencies even in debug builds (does not affect workspace packages):
[profile.dev.package."*"]
opt-level = 2

[workspace.dependencies]
rayon = "1.8.0"
