[workspace]
members = [
   "common",
   "day01",
   "day02",
   "day03",
   "day04",
]


# Optimize all dependencies even in debug builds (does not affect workspace packages):
[profile.dev.package."*"]
opt-level = 2
