[package]
name = "day17"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common.workspace = true
num-traits = "0.2"
num-derive = "0.4"
